name: 'Gepety Scan Action'
description: 'Run GPT powered code analysis'
inputs:
  repo-name:
    description: |
      Repository name. 
      This must match the path it is checked out in the GitHub Workspace'
    required: true
runs:
  using: 'composite' 
  steps:
    - name: Check out this action's repository
      uses: actions/checkout@v4
      with:
        repository: MetaMask/gepety-scan-action
        path: scanner

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      working-directory: ${{github.action_path}}
      run: yarn --immutable
      shell: bash

    - name: Build
      working-directory: ${{github.action_path}}
      run: yarn build
      shell: bash

    - name: Execute
      id: execute
      run: |
        node ${{github.action_path}}/dist/entrypoint.js
      shell: bash
      env:
        REPO_NAME: ${{ inputs.repo-name }}
