name: 'Gepety Scan Action'
description: 'Run GPT powered code analysis'
inputs:
  repo-name:
    description: |
      Repository name. 
      This must match the path it is checked out in the GitHub Workspace'
    required: true
runs:
  using: 'composite' 
  steps:
    - name: Check out this action's repository
      uses: actions/checkout@v4
      with:
        repository: MetaMask/gepety-scan-action
        path: scanner
    - name: Execute
      id: execute
      run: |
        node $GITHUB_WORKSPACE/scanner/scripts/entrypoint.js
      shell: bash
      env:
        REPO_NAME: ${{ inputs.repo-name }}
