name: 'Gepety Scan Action'
description: 'Run GPT powered code analysis'
inputs:
  repo-name:
    description: |
      Repository name. 
      This must match the path it is checked out in the GitHub Workspace'
    required: true
runs:
  using: 'composite' 
  steps:
    ## This ensures that clients running gepety-scan-action@<somebranch>
    ## will always use the branch specified
    - name: Copy action into workspace
      run: |
        cd ${{ github.workspace }}
        mkdir gepety-scan-action
        cp -r ${{github.action_path}}/* ./gepety-scan-action
      shell: bash
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Setup
      working-directory: ./gepety-scan-action
      run: yarn --immutable && yarn build
      shell: bash

    - name: Execute
      uses: actions/github-script@v7
      with:
        action-path: ${{github.action_path}}
        script: |   
          const entrypoint = require('./gepety-scan-action/dist/entrypoint.js');
          await entrypoint({ github, context});